description: "Настройки пользователя"
get:
    description: "Получить настройки"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/one.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/one-response-body.json
put:
    securedBy: [bearerAuth]
    description: "Изменить настройки"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/update.raml
    body:
        application/json:
            example: !include example/update-request-body.json
