description: "Файловое хранилище"
get:
    description: "Получть список файлов"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/all.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/all-response-body.json
post:
    securedBy: [bearerAuth]
    description: "Загрузить файл на сервер"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/create.raml
    body:
        multipart/form-data:
            properties:
                service_id:
                    description: ID сервиса
                    required: true
                    type: integer
                file:
                    description: Файл для загрузки
                    required: true
                    type: file
/{id}:
    uriParameters:
        id:
            description: "ID файла"
            type: integer
    get:
        description: "Получить файл"
        is: !include ../../../../vendor/zndoc/rest-api/src/is/one.raml
        responses:
            200:
                body:
                    application/json:
                        example: !include example/one-response-body.json
    put:
        securedBy: [bearerAuth]
        description: "Изменить файл"
        is: !include ../../../../vendor/zndoc/rest-api/src/is/update.raml
        body:
            application/json:
                example: !include example/update-request-body.json
    delete:
        securedBy: [bearerAuth]
        description: "Удалить файл"
        is: !include ../../../../vendor/zndoc/rest-api/src/is/delete.raml
