description: "Аутентификация"
post:
    description: "Получение токена"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/post200.raml
    body:
        application/json:
            example: !include example/post-request-body.json
    responses:
        200:
            description: "Аутентификация прошла успешно"
            body:
                application/json:
                    example: !include example/post-response-body.json
            headers:
                Authorization:
                    description: Токен авторизации
                    type: string
                    example: "bearer ucboG8yfWKsd7DljVHHJjGMl3t6UZAL0"

get:
    securedBy: [bearerAuth]
    description: Получение информации текущего пользователя
    is: !include ../../../../vendor/zndoc/rest-api/src/is/simple/one.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/one-reponse-body.json
