description: "Аутентификация"
post:
    description: "Получение токена"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/post200.raml
    body:
        application/json:
            example: !include example/post-request-body.json
    responses:
        200:
            description: "Аутентификация прошла успешно"
            body:
                application/json:
                    example: !include example/post-response-body.json
            headers:
                    Authorization:
                        description: Токен авторизации
                        type: string
                        example: "c0bec554c5dda6a9cefc06dd6d65d3de"

get:
    securedBy: [Auth]
    description: Получение информации текущего пользователя
    is: !include ../../../../vendor/zndoc/rest-api/src/is/simple/one.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/one-reponse-body.json
