description: "Уведомления для тестировщиков"
get:
    securedBy: [bearerAuth]
    queryParameters:
        type:
            description: "Тип уведомления (sms, email)"
            type: string
    description: "Получить список уведомлений"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/all.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/all-response-body.json
delete:
    securedBy: [bearerAuth]
    description: "Очистить уведомления"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/delete.raml
