description: "Пользователи"
/{id}:
    uriParameters:
        id:
            description: "ID пользователя"
            type: integer
    get:
        description: "Возвращает пользователя"
        is: !include ../../../../vendor/zndev/rest-api/src/is/simple/one.raml
        responses:
            200:
                body:
                    application/json:
                        example: !include example/one-reponse-body.json