description: "Изменить почту"
put:
    securedBy: [bearerAuth]
    description: "Изменить почту"
    is: !include ../../../../vendor/zndoc/rest-api/src/is/update.raml
    body:
        application/json:
            example: !include example/email/update-request-body.json