description: "RBAC. Связи ролей с пользователями"
get:
    description: "Получть связей"
    is: !include ../../../../vendor/zndev/rest-api/src/is/all.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/all-response-body.json
post:
    securedBy: [Auth]
    description: "Создать связь"
    is: !include ../../../../vendor/zndev/rest-api/src/is/create.raml
    body:
        application/json:
            example: !include example/create-request-body.json

/{name}:
    uriParameters:
        name:
            description: "Имя связи"
            type: string
    get:
        description: "Получить связь"
        is: !include ../../../../vendor/zndev/rest-api/src/is/one.raml
        responses:
            200:
                body:
                    application/json:
                        example: !include example/one-response-body.json
    put:
        securedBy: [Auth]
        description: "Изменить связь"
        is: !include ../../../../vendor/zndev/rest-api/src/is/update.raml
        body:
            application/json:
                example: !include example/update-request-body.json
    delete:
        securedBy: [Auth]
        description: "Удалить связь"
        is: !include ../../../../vendor/zndev/rest-api/src/is/delete.raml
