description: "Восстановление пароля"
/request-activation-code:
    post:
        description: "Запрос кода активации"
        is: !include ../../../../vendor/zndev/rest-api/src/is/create.raml
        body:
            application/json:
                example: !include example/request-activation-code.json
        responses:
            202:
                description: |
                    СМС-код был отправлен ранее.
                    Повторите попытку через некоторое время.
/verify-activation-code:
    post:
        description: "Верификация кода активации"
        is: [lang, timezone, code204, code400, code422, code500]
        body:
            application/json:
                example: !include example/verify-activation-code.json
/set-password:
    post:
        description: "Сохранение нового пароля"
        is: !include ../../../../vendor/zndev/rest-api/src/is/create.raml
        body:
            application/json:
                example: !include example/set-password.json