description: "Временное хранилище файлов пользователя"
post:
    securedBy: [Auth]
    description: "Загрузить файл на сервер"
    is: !include ../../../../vendor/zndev/rest-api/src/is/create.raml
    body:
        multipart/form-data:
            properties:
                file:
                    description: Файл для загрузки
                    required: true
                    type: file
