#%RAML 1.0
title: Example host
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://api.example.com/v1

mediaType: [ application/json ]

securitySchemes:
  Auth: !include ../vendor/zndev/rest-api/src/securitySchemes/base.raml
#securedBy: [ Auth ]

traits:
  paged:   !include ../vendor/zndev/rest-api/src/traits/paged.raml
  search:  !include ../vendor/zndev/rest-api/src/traits/search.raml
  lang:    !include ../vendor/zndev/rest-api/src/traits/lang.raml
  timezone: !include ../vendor/zndev/rest-api/src/traits/timezone.raml
  fields:  !include ../vendor/zndev/rest-api/src/traits/fields.raml
  expand:  !include ../vendor/zndev/rest-api/src/traits/expand.raml
  code200: !include ../vendor/zndev/rest-api/src/traits/codes/200.raml
  code201: !include ../vendor/zndev/rest-api/src/traits/codes/201.raml
  code204: !include ../vendor/zndev/rest-api/src/traits/codes/204.raml
  code304: !include ../vendor/zndev/rest-api/src/traits/codes/304.raml
  code400: !include ../vendor/zndev/rest-api/src/traits/codes/400.raml
  code401: !include ../vendor/zndev/rest-api/src/traits/codes/401.raml
  code403: !include ../vendor/zndev/rest-api/src/traits/codes/403.raml
  code404: !include ../vendor/zndev/rest-api/src/traits/codes/404.raml
  code405: !include ../vendor/zndev/rest-api/src/traits/codes/405.raml
  code415: !include ../vendor/zndev/rest-api/src/traits/codes/415.raml
  code422: !include ../vendor/zndev/rest-api/src/traits/codes/422.raml
  code429: !include ../vendor/zndev/rest-api/src/traits/codes/429.raml
  code500: !include ../vendor/zndev/rest-api/src/traits/codes/500.raml

/auth: !include user/v1/auth/api.raml
/registration: !include user/v1/registration/api.raml
