description: "Изменить пароль"
put:
    securedBy: [Auth]
    description: "Изменить пароль"
    is: !include ../../../../vendor/zndev/rest-api/src/is/update.raml
    body:
        application/json:
            example: !include example/password/update-request-body.json